function Nm_xi = Nm_2412_xi(xi,eta)
%Nm_2412_xi
%    Nm_xi = Nm_2412_xi(XI,ETA)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    21-Sep-2026 14:56:10

t2 = eta./4.0;
t3 = -t2;
t4 = t2+1.0./4.0;
t6 = t2-1.0./4.0;
t5 = t3+1.0./4.0;
t7 = t3-1.0./4.0;
Nm_xi = reshape([t6,0.0,0.0,t6,t5,0.0,0.0,t5,t4,0.0,0.0,t4,t7,0.0,0.0,t7],[2,8]);
end
