function dFeS = dFe_2412S(E,nu,Lz,in4,in5,xi,eta)
%dFe_2412S
%    dFeS = dFe_2412S(E,NU,Lz,IN4,IN5,XI,ETA)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    07-Oct-2026 01:08:31

dFeS = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0];
end
